# -*- coding: utf-8 -*-
"""Heat2bot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uOYyT59WvgVtSTFdjzOxdo9Tn_Oyx5cv
"""

# Persona extractor tailored for your Personachat (Persona + chat) and ESConv (dialog -> content)
# Save as persona_extractor_debug.py and run in Colab / notebook (upload files to /content)

import os, json, torch
from transformers import (
    AutoTokenizer, AutoModelForSeq2SeqLM,
    Seq2SeqTrainer, Seq2SeqTrainingArguments, DataCollatorForSeq2Seq
)
from datasets import Dataset
from tqdm import tqdm

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Using device:", device)

persona_file = "/content/personachat.json"
esconv_file  = "/content/ESConv.json"

# Load PersonaChat -> history -> persona
# -------------------------
def load_personachat_history2persona(path, max_examples=None):
    data = json.load(open(path, "r", encoding="utf-8"))
    examples = []
    for item in data:
        # Persona text: you have "Persona" key in your sample
        persona_text = ""
        # common keys in your sample: "Persona"
        for k in ["Persona", "persona", "personality"]:
            if k in item and item[k]:
                val = item[k]
                if isinstance(val, list):
                    persona_text = " | ".join([v.strip() for v in val if isinstance(v, str) and v.strip()])
                else:
                    persona_text = str(val).strip()
                break

        # chat: your sample has "chat" as newline-separated string
        chat = item.get("chat") or item.get("dialog") or item.get("dialogue") or item.get("utterances") or ""
        turns = []
        if isinstance(chat, str):
            turns = [t.strip() for t in chat.split("\n") if t.strip()]
        elif isinstance(chat, list):
            for u in chat:
                if isinstance(u, str):
                    turns.append(u.strip())
                elif isinstance(u, dict):
                    txt = u.get("content") or u.get("text") or u.get("utterance") or ""
                    if txt:
                        turns.append(str(txt).strip())

        if not persona_text or not turns:
            continue

        src = "history: " + " </s> ".join(turns)
        tgt = persona_text
        examples.append({"source": src, "target": tgt})
        if max_examples and len(examples) >= max_examples:
            break

    print(f"[INFO] Loaded {len(examples)} history->persona examples from {path}")
    return examples

# Quick check on PersonaChat loader
# -------------------------
persona_examples = load_personachat_history2persona(persona_file, max_examples=20000)
if len(persona_examples) == 0:
    raise SystemExit("ERROR: No history->persona examples found. Check your personachat.json keys (Persona/chat).")

print("\n=== SAMPLE TRAINING PAIRS (first 5) ===")
for i, ex in enumerate(persona_examples[:5]):
    print(f"\n[{i+1}] SOURCE (trunc): {ex['source'][:200]}")
    print(f"[{i+1}] TARGET (persona): {ex['target'][:200]}")

# Trim for quick runs (optional)
persona_examples = persona_examples[:15000]
n = len(persona_examples)
train_ds = Dataset.from_list(persona_examples[:int(0.9*n)])
val_ds   = Dataset.from_list(persona_examples[int(0.9*n):])

# Model & Tokenization
# -------------------------
model_name = "facebook/bart-base"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name).to(device)

def tokenize_fn(batch):
    model_inputs = tokenizer(batch["source"], truncation=True, max_length=512)
    # correct seq2seq target tokenization
    with tokenizer.as_target_tokenizer():
        labels = tokenizer(batch["target"], truncation=True, max_length=128)
    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

# Inspect tokenized labels for a small sample to detect -100 or empty targets
sample_check = Dataset.from_list(persona_examples[:4])
sample_tok = sample_check.map(tokenize_fn, batched=True, remove_columns=sample_check.column_names)
print("\n=== TOKENIZED LABELS SAMPLE ===")
for i, item in enumerate(sample_tok):
    labels = item["labels"]
    print(f"Example {i+1}: label tokens len={len(labels)} preview={labels[:20]}")
    if len(labels) == 0 or all([lbl == -100 for lbl in labels]):
        raise SystemExit("ERROR: tokenized labels appear empty or all -100. That means target tokenization failed or target is empty.")

train_tokenized = train_ds.map(tokenize_fn, batched=True, remove_columns=train_ds.column_names)
val_tokenized   = val_ds.map(tokenize_fn,   batched=True, remove_columns=val_ds.column_names)

# Sanity generation BEFORE training (should produce something but likely not persona-yet)
# -------------------------
def generate_from_text(inp_text, max_len=128):
    inputs = tokenizer(inp_text, return_tensors="pt", truncation=True, max_length=512).to(device)
    model.eval()
    with torch.no_grad():
        ids = model.generate(**inputs, max_length=max_len, num_beams=4, early_stopping=True, min_length=1)
    return tokenizer.decode(ids[0], skip_special_tokens=True).strip()

print("\n=== SANITY GENERATE (pre-train) on first source ===")
test_src = persona_examples[0]["source"]
print("SOURCE (trunc):", test_src[:200])
print("MODEL OUTPUT (pre-train):", repr(generate_from_text(test_src)))

# ===================================================
# TRAIN ON FULL PERSONACHAT → TEST ON FULL ESConv
# ===================================================

import json
import torch
from tqdm import tqdm
from datasets import Dataset
from transformers import (
    BartForConditionalGeneration,
    BartTokenizer,
    Seq2SeqTrainer,
    Seq2SeqTrainingArguments,
    DataCollatorForSeq2Seq
)

device = "cuda" if torch.cuda.is_available() else "cpu"

# -----------------------------
# 1. LOAD PERSONACHAT DATA
# -----------------------------
personachat_path = "/content/personachat.json"
with open(personachat_path, "r", encoding="utf-8") as f:
    persona_raw = json.load(f)

print("Loaded PersonaChat entries:", len(persona_raw))

# Each entry has keys: "", "Persona", "chat"
def process_personachat_entry(entry):
    persona = entry.get("Persona", "").strip()
    chat_text = entry.get("chat", "").strip()
    if not persona or not chat_text:
        return None

    # Split chat into utterances
    turns = [t.strip() for t in chat_text.split("\n") if t.strip()]
    if len(turns) < 2:
        return None

    # Input = Persona + conversation history (except last)
    # Target = last utterance
    src = f"persona: {persona}  history: {' </s> '.join(turns[:-1])}"
    tgt = turns[-1]
    return {"source": src, "target": tgt}

processed_data = [d for d in (process_personachat_entry(x) for x in persona_raw) if d]
print("Processed PersonaChat samples:", len(processed_data))

dataset = Dataset.from_list(processed_data)

# -----------------------------
# 2. LOAD MODEL & TOKENIZER
# -----------------------------
model_name = "facebook/bart-base"
tokenizer = BartTokenizer.from_pretrained(model_name)
model = BartForConditionalGeneration.from_pretrained(model_name)

# -----------------------------
# 3. TOKENIZE
# -----------------------------
def preprocess_function(examples):
    model_inputs = tokenizer(
        examples["source"], truncation=True, padding="max_length", max_length=512
    )
    labels = tokenizer(
        examples["target"], truncation=True, padding="max_length", max_length=128
    )
    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

tokenized = dataset.map(preprocess_function, batched=True, remove_columns=dataset.column_names)

# -----------------------------
# 4. TRAINING
# -----------------------------
args = Seq2SeqTrainingArguments(
    output_dir="./persona_bart_full",
    per_device_train_batch_size=4,
    num_train_epochs=3,
    logging_steps=100,
    save_steps=500,
    save_total_limit=2,
    report_to="none",
    remove_unused_columns=False
)

data_collator = DataCollatorForSeq2Seq(tokenizer, model)

trainer = Seq2SeqTrainer(
    model=model,
    args=args,
    train_dataset=tokenized,
    tokenizer=tokenizer,
    data_collator=data_collator,
)

print("\n=== START TRAINING ON FULL PERSONACHAT ===")
trainer.train()
trainer.save_model("./persona_bart_full")
tokenizer.save_pretrained("./persona_bart_full")
print("Training complete and model saved.")

# ===================================================
# 5. INFERENCE ON FULL ESConv
# ===================================================

esconv_path = "/content/ESConv.json"
with open(esconv_path, "r", encoding="utf-8") as f:
    esconv_data = json.load(f)

print("Loaded ESConv dialogues:", len(esconv_data))
model.to(device)
model.eval()

def extract_esconv_texts(dialog):
    """Extract the dialogue utterances from ESConv entry."""
    utterances = []
    if isinstance(dialog, dict) and "dialog" in dialog:
        for turn in dialog["dialog"]:
            content = turn.get("content", "").strip()
            if content:
                utterances.append(content)
    return utterances

def compose_input(history_texts):
    return "history: " + " </s> ".join(history_texts)

def infer_persona(dialog_entry):
    utterances = extract_esconv_texts(dialog_entry)
    if not utterances:
        return ""

    inp = compose_input(utterances)
    inputs = tokenizer(inp, return_tensors="pt", truncation=True, max_length=512).to(device)
    with torch.no_grad():
        ids = model.generate(**inputs, max_length=128, num_beams=4, early_stopping=True)
    return tokenizer.decode(ids[0], skip_special_tokens=True).strip()

output = []
for dlg in tqdm(esconv_data, desc="Generating personas from ESConv"):
    persona_pred = infer_persona(dlg)
    output.append({"dialog": dlg, "generated_persona": persona_pred})

with open("PESConv_full.json", "w", encoding="utf-8") as f:
    json.dump(output, f, ensure_ascii=False, indent=2)

print("PESConv_full.json saved.")

